Improve build error message

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,5 +1,9 @@
 #! /usr/bin/env sh
-[ -n "$CXX" ] && (
+[ -n "$CXX" ] || (
+  echo 'Missing environment variable CXX' >&2
+  echo 'CXX variable should points to a GCC-like C++ compiler' >&2
+  exit 1
+) && (
   (
     libversion=$(pkg-config --modversion gtkmm-3.0) || exit $?
     echo Using GTKmm version $libversion
@@ -13,8 +17,4 @@
     echo 'failed.'
     exit $code
   )
-) || (
-  echo 'Missing environment variable CXX' >&2
-  echo 'CXX variable should points to a GCC-like C++ compiler' >&2
-  exit 1
 )
